services:
  - type: web
    name: akash-birthday
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    numInstances: 1
    healthCheckPath: /
